### ISSUE TITLE
checkout - file may be deleted

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#44]
after 'checkout' any file can be absent  - ie all opened files in Cud can be deleted. do we handle it?
@veksha

**Comment by veksha** [comment]
I think, this is responsibility of Cuda to detect the file changes from the "outside".
git_status icon will not show up for deleted file that is still opened in tab.

we can have something similar to this badge, but for deletion:
![image](https://user-images.githubusercontent.com/275333/171367770-602976a9-3cea-4312-ac89-11b483abdbde.png)
"File has been deleted: file.py"
and instead of Reload button there will be "Close file" button. or "Save as" button.

**Comment by Alexey-T** [comment]
You are right, it’s Cud task, sorry to bother you

**Comment by veksha** [comment]
2. detect that file was deleted -> change tab title to "file (deleted from disk)". and when user will try to save file (ctrl+s) ->  Cud will open "Save As" dialog. so user will immediately know that this file doesn't exist.

**Comment by Alexey-T** [comment]
A. Tab title is already marked by star-char (controlled by option). 
It’s not enough ?

b. Save-as dialog for deleted file? What editors do that?

**Comment by veksha** [comment]
personally I wouldn't change anything about it. it is up to user to keep track of his opened tabs/files and branches.
any intrusive messages are inappropriate. so the only way is some "passive clue". like let the tab forget about its connectnion to file on the disk. (like any new tab, Ctrl+N has no connection to disk yet, so "save as" dialog will appear on ctrl+s)
